apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctech-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abctech
  template:
    metadata:
      labels:
        app: abctech
    spec:
      containers:
      - name: abc-technologies
        image: marekczajkowski992/abctech:latest
        ports:
        - containerPort: 80