apiVersion: v1
kind: Service
metadata:
  name: abctech-nodeport
spec:
  selector:
    app: abctech
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 4789
      nodePort: 31778
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: abctech-lbalancer
spec:
  selector:
    app: abctech
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 4789
      nodePort: 31644
  type: LoadBalancer
