apiVersion: v1
kind: Service
metadata:
  name: abctech-svc
spec:
  selector:
    app: abctech
  ports:
    - protocol: TCP
      port: 4789
      targetPort: 8080
      nodePort: 31778
  type: NodePort
