apiVersion: v1
kind: Service
metadata:
  name: abctech-nodeport
spec:
  selector:
    app: abctech
  ports:
    - protocol: TCP
      port: 4789
      targetPort: 8080
      nodePort: 31778
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: abctech-lbalancer
spec:
  selector:
    app: abctech
  ports:
    - protocol: TCP
      port: 4789
      targetPort: 8080
      nodePort: 31644
  type: LoadBalancer
